# Add custom stopwords to be joined with general stopwords
# generated from word count of corpus 07/20/2020
custom_stopwords = [
    "ch",
    "section",
    "i",
    "ii",
    "iii",
    "iv",
    "v",
    "chapter",
    "subsection",
    "subsec",
    "paragraph",
    "emphasis",
    "title",
    "date",
    "shall",
    "stat",
    # "secretary",
    # "act",
    # "states",
    # "united",
    "date",
    "state",
    "provided",
    "effective",
    # "amendment",
    # "federal",
    "year",
    # "dod",
    "substituted",
    # "service",
    "provisions",
    "set",
    "general",
    # "program",
    "information",
    "added",
    "services",
    "note",
    "oct",
    # "defense",
    # "national",
    # "agency",
    "including",
    # "department",
    # "public",
    # "plan",
    "amended",
    "term",
    # "respect",
    # "security",
    # "use",
    # "person",
    "dec",
    # "health",
    "prior",
    # "code",
    # "period",
    # "purposes",
    # "requirements",
    # "law",
    # "appropriate",
    # "government",
    # "required",
    # "fiscal",
    # "provide",
    "described",
    "aug",
    "report",
    "authority",
    # "military",
    "years",
    "par",
    # "amendments",
    # "authorized",
    "applicable",
    "related",
    "subchapter",
    # "pursuant",
    # "individual",
    # "case",
    "assistance",
    "sections",
    # "regulations",
    "july",
    "time",
    # "property",
    # "programs",
    "means",
    "order",
    "accordance",
    # "office",
    "referred",
    # "activities",
    # "management",
    "available",
    "div",
    "reference",
    "june",
    # "subject",
    # "commission",
    "nov",
    "subparagraph",
    # "committee",
    # "apply",
    # "funds",
    # "development",
    # "board",
    # "director",
    # "congress",
    # "foreign",
    # "necessary",
    # "personnel",
]
