from collections import defaultdict


DISPLAY_TYPE_LOOKUP = defaultdict(lambda: "Document", {
    "dod": 'Issuance',
    "dodm": 'Manual',
    "dodi": 'Instruction',
    "dodd": 'Directive',
    "cjcs": 'Notice',
    "cjcsi": 'Instruction',
    "cjcsm": 'Manual',
    "cjcsg": 'Guide',
    "icd": 'Directive',
    "icpg": 'Guide',
    "icpm": 'Manual',
    "title": 'Title',
    "dep": 'Memorandum',
    "sec": 'Memorandum',
    "ai": 'Instruction',
    "dtm": 'Memorandum',
    "eo": 'Order',
    "organization": 'Organization',
    "person": 'Person',
    "ombm": 'Memorandum',
    "opnavnote": 'Notice',
    "secnavnote": 'Notice',
    "opnavinst": 'Instruction',
    "secnavinst": 'Instruction',
    "comnavresforcominst": 'Instruction',
    "comnavresforcomnote": 'Notice',
    "navmed": 'Manual',
    "bumednote": 'Notice',
    "bumedinst": 'Instruction',
    "h.con.res.": 'Legislation',
    "h.j.res.": 'Legislation',
    "h.r.": 'Legislation',
    "h. res.": 'Legislation',
    "s.": 'Legislation',
    "s. con. res.": 'Legislation',
    "s.j. res.": 'Legislation',
    "s. res.": 'Legislation',
    "usar cir": 'Circular',
    "usar pam": 'Pamphlet',
    "usar reg": 'Regulation',
    "memo": "Memorandum",
    "dfar": "Regulation",
    "far": "Regulation",
    "cngbi": "Instruction",
    "cim": "Manual"
})


CRAWLER_TO_DISPLAY_ORG_LOOKUP = defaultdict(lambda: "Uncategorized", {
    "dod_issuances": "Dept. of Defense",
    "jcs_pubs": 'Joint Chiefs of Staff',
    "jcs_manual_uploads": 'Joint Chiefs of Staff',
    "dod_manual_uploads": 'Dept. of Defense',
    "army_manual_uploads": 'US Army',
    "ic_policies": 'Intelligence Community',
    "us_code": 'United States Code',
    "ex_orders": 'Executive Branch',
    "opm_pubs": "OPM",
    "air_force_pubs": 'Dept. of the Air Force',
    "army_pubs": 'US Army',
    "marine_pubs": 'US Marine Corps',
    "secnav_pubs": 'US Navy',
    "navy_reserves": 'US Navy Reserve',
    "navy_med_pubs": 'US Navy Medicine',
    "Bupers_Crawler": 'US Navy',
    "milpersman_crawler": "US Navy",
    "nato_stanag": "NATO",
    "fmr_pubs": "FMR",
    "legislation_pubs": "Congress",
    "Army_Reserve": "US Army",
    "Memo": "Dept. of Defense",
    "dha_pubs": "Defense Health Agency",
    "jumbo_DFAR": "DFAR",
    "jumbo_FAR": "FAR",
    "National_Guard": "National Guard",
    "Coast_Guard": "Coast Guard"
})
