import uuid



def process_rdte(data: dict) -> dict:
    data_value = {
        'id': str(uuid.uuid4()),
        'Budget_Year': data.get('BudgetYear'),
        'Budget_Cycle': data.get('BudgetCycle'),
        'Submission_Date': None,
        'Service__Agency': data.get('OrganizationCode'),
        'Service__Agency_Name': data.get('Organization'),
        'Appropriation': data.get('Appn_Num'),
        'Appropriation_Title': data.get('Appn_Title'),
        'Budget_Activity': data.get('BA_Number'),
        'Budget_Activity_Title': data.get('BA_Title'),
        'Program_Element': data.get('PE_Num'),
        'Program_Element_Title': data.get('PE_Title'),
        'Program_Element_Notes': None,
        'PE_Mission_Description_and_Budget_Justification': data.get('PE_MSN_Dsec'),
        'Project': data.get('R1_Line_Num'),
        'Project_Title': None,
        'Project_Mission_Description': data.get('PE_MDAP_Code'),
        'Prior_Year_Amount': data.get('PEFund_PY'),
        'Current_Year_Amount': data.get('PEFund_CY'),
        'Budget_Year_1': data.get('PEFund_BY1'),
        'Budget_Year_2': data.get('PEFund_BY2'),
        'Budget_Year_3': data.get('PEFund_BY3'),
        'Budget_Year_4': data.get('PEFund_BY4'),
        'Budget_Year_5': data.get('PEFund_BY5'),
        'To_Complete': data.get('PEFund_CTC'),
        'Total_Cost': data.get('PEFund_Total'),
        'Project_Notes': None,
        'Project_Aquisition_Strategy': None,
        'Project_Perfromance_Metircs': None,
        'Other_program_funding_summary_remarks': None,
        'Program_Element_Title_Map': None,
        'Program_Element_Title_Count': None,
        'PE_Mission_Description_and_Budget_Justification_Map': None,
        'PE_Mission_Description_and_Budget_Justification_Count': None,
        'Project_Title_Map': None,
        'Project_Title_Count': None,
        'Project_Mission_Description_Map': None,
        'Project_Mission_Description_Count': None,
        'Project_Notes_Map': None,
        'Project_Notes_Count': None,
        'Project_Aquisition_Strategy_Map': None,
        'Project_Aquisition_Strategy_Count': None,
        'Project_Perfromance_Metircs_Map': None,
        'Project_Perfromance_Metircs_Count': None,
        'Other_program_funding_summary_remarks_Map': None,
        'Other_program_funding_summary_remarks_Count': None,
        'core_ai_label': None,
        'jaic_review_stat': None,
        'jaic_review_notes': None,
        'reviewer': None,
        'source_tag': None,
        'planned_trans_part': None,
        'current_msn_part': None,
        'service_review': None,
        'adj_core_ai_label': None
    }
    return data_value

